export const GITHUB_TOKEN_KEY = 'githubPersonalAccessToken';

export interface CreateGistOptions {
  token: string;
  description: string;
  isPublic: boolean;
  filename: string;
  content: string;
}

export interface GistResult {
  id: string;
  url: string;
  htmlUrl: string;
}

/**
 * Retrieve saved GitHub Personal Access Token from chrome storage
 */
export async function getGitHubToken(): Promise<string> {
  try {
    if (typeof chrome !== 'undefined' && chrome.storage?.local) {
      const data = await chrome.storage.local.get(GITHUB_TOKEN_KEY);
      return (data && (data[GITHUB_TOKEN_KEY] as string)) || '';
    }
    return '';
  } catch (_) {
    return '';
  }
}

/**
 * Save GitHub Personal Access Token to chrome storage
 */
export async function saveGitHubToken(token: string): Promise<void> {
  if (typeof chrome !== 'undefined' && chrome.storage?.local) {
    await chrome.storage.local.set({ [GITHUB_TOKEN_KEY]: token.trim() });
  }
}

/**
 * Publish a file directly to GitHub Gist
 */
export async function createGitHubGist(options: CreateGistOptions): Promise<GistResult> {
  const { token, description, isPublic, filename, content } = options;

  if (!token || !token.trim()) {
    throw new Error('GitHub Personal Access Token is required.');
  }

  const cleanFilename = filename.replace(/^\/+/, '') || 'artifact.txt';

  const bodyPayload = {
    description: description?.trim() || `Generated by SAM-Agent: ${cleanFilename}`,
    public: isPublic,
    files: {
      [cleanFilename]: {
        content: content || ' ',
      },
    },
  };

  const res = await fetch('https://api.github.com/gists', {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
      'Accept': 'application/vnd.github+json',
      'Authorization': `Bearer ${token.trim()}`,
      'X-GitHub-Api-Version': '2022-11-28',
    },
    body: JSON.stringify(bodyPayload),
  });

  if (!res.ok) {
    const errorBody = await res.json().catch(() => ({}));
    if (res.status === 401) {
      throw new Error('Bad credentials (401). Please check that your GitHub token is valid and has "gist" scope.');
    }
    throw new Error(`GitHub API Error (${res.status}): ${errorBody.message || res.statusText}`);
  }

  const data = await res.json();

  return {
    id: data.id,
    url: data.url,
    htmlUrl: data.html_url,
  };
}
